<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.ps_eventbus.installer' shared service.

return $this->services['mbo.ps_eventbus.installer'] = new \PrestaShop\Module\Mbo\Service\ModuleInstaller('ps_eventbus');
