<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.ps_accounts.installer' shared service.

return $this->services['mbo.ps_accounts.installer'] = new \PrestaShop\PsAccountsInstaller\Installer\Installer('5.2.5');
