<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_accounts.facade' shared service.

return $this->services['ps_accounts.facade'] = new \ps_metrics_module_v4_0_9\PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts(${($_ = isset($this->services['ps_accounts.installer']) ? $this->services['ps_accounts.installer'] : ($this->services['ps_accounts.installer'] = new \ps_metrics_module_v4_0_9\PrestaShop\PsAccountsInstaller\Installer\Installer('5.0'))) && false ?: '_'});
