<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.http.client.factory' shared service.

return $this->services['ps_checkout.http.client.factory'] = new \PrestaShop\Module\PrestashopCheckout\Http\HttpClientFactory();
