<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsxMarketingWithGoogle\ProductFilter\FilterApplication\ProductEnumerator' shared service.

return $this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\ProductFilter\\FilterApplication\\ProductEnumerator'] = new \PrestaShop\Module\PsxMarketingWithGoogle\ProductFilter\FilterApplication\ProductEnumerator(${($_ = isset($this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\ProductFilter\\FilterApplication\\FilterValidator']) ? $this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\ProductFilter\\FilterApplication\\FilterValidator'] : ($this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\ProductFilter\\FilterApplication\\FilterValidator'] = new \PrestaShop\Module\PsxMarketingWithGoogle\ProductFilter\FilterApplication\FilterValidator())) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\ProductFilter\\FilterApplication\\QueryBuilder']) ? $this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\ProductFilter\\FilterApplication\\QueryBuilder'] : $this->load('getQueryBuilderService.php')) && false ?: '_'});
