<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.http.client' shared service.

return $this->services['ps_checkout.http.client'] = ${($_ = isset($this->services['ps_checkout.http.client.factory']) ? $this->services['ps_checkout.http.client.factory'] : ($this->services['ps_checkout.http.client.factory'] = new \PrestaShop\Module\PrestashopCheckout\Http\HttpClientFactory())) && false ?: '_'}->create(${($_ = isset($this->services['ps_checkout.http.client.configuration']) ? $this->services['ps_checkout.http.client.configuration'] : $this->load('getPsCheckout_Http_Client_ConfigurationService.php')) && false ?: '_'});
