<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsxMarketingWithGoogle\Conversion\UserDataProvider' shared service.

return $this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Conversion\\UserDataProvider'] = new \PrestaShop\Module\PsxMarketingWithGoogle\Conversion\UserDataProvider(${($_ = isset($this->services['psxmarketingwithgoogle.customer']) ? $this->services['psxmarketingwithgoogle.customer'] : $this->load('getPsxmarketingwithgoogle_CustomerService.php')) && false ?: '_'}, ${($_ = isset($this->services['psxmarketingwithgoogle.cart']) ? $this->services['psxmarketingwithgoogle.cart'] : $this->load('getPsxmarketingwithgoogle_CartService.php')) && false ?: '_'});
