services:
  mysql:
    container_name: ebiz-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - test-db:/var/lib/mysql
  prestashop:
    container_name: ebiz-prestashop
    image: prestashop/prestashop:1.7.8
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
      - 8443:443
    environment:
      DB_SERVER: ebiz-mysql
      DB_NAME: prestashop
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080 # HAS TO BE ':8080'
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN}
      PS_COUNTRY: PL
      PS_LANGUAGE: pl
    networks:
      - prestashop_network
    volumes:
      - ./../../prestashop:/var/www/html
      - ./../../config/sites-available:/etc/apache2/sites-available
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
        reservations:
          cpus: '1.0'
          memory: 256M

  memcached:
    image: memcached
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    networks:
      - prestashop_network


networks:
  prestashop_network:
volumes:
  test-db: