services:
  mysql:
    container_name: ebiz-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - db:/var/lib/mysql
  prestashop:
    container_name: ebiz-prestashop
    image: prestashop/prestashop:1.7.8
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: ebiz-mysql
      DB_NAME: prestashop
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN}
      PS_COUNTRY: PL
      PS_LANGUAGE: pl
    networks:
      - prestashop_network
    volumes:
      - ./../../prestashop:/var/www/html
networks:
  prestashop_network:
volumes:
  db: