services:
    _defaults:
        public: true

    ##############
    # Your Module

    smartargetbuttonbuilder.module:
        class: smartargetbuttonbuilder
        factory: ['Module', 'getInstanceByName']
        arguments:
            - 'smartargetbuttonbuilder'

    smartargetbuttonbuilder.context:
        class: Context
        factory: ['Context', 'getContext']

    #####################
    # PrestaShop Account
    smartargetbuttonbuilder.ps_accounts_installer:
        class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
        arguments:
            - '5.0'

    smartargetbuttonbuilder.ps_accounts_facade:
        class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
        arguments:
            - '@smartargetbuttonbuilder.ps_accounts_installer'

    #####################
    # PrestaShop Billing

    smartargetbuttonbuilder.ps_billings_context_wrapper:
        class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
        arguments:
            - '@smartargetbuttonbuilder.ps_accounts_facade'
            - '@smartargetbuttonbuilder.context'
            - false # if true, enables the sandbox mode, if false or empty, disables it

    smartargetbuttonbuilder.ps_billings_facade:
        class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
        public: true
        arguments:
            - '@smartargetbuttonbuilder.ps_billings_context_wrapper'
            - '@smartargetbuttonbuilder.module'

    # Remove this if you do not need BillingService
    smartargetbuttonbuilder.ps_billings_service:
        class: 'PrestaShopCorp\Billing\Services\BillingService'
        public: true
        arguments:
            - '@smartargetbuttonbuilder.ps_billings_context_wrapper'
            - '@smartargetbuttonbuilder.module'
